version: '3'
services:
  cloud:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/docker_django
    restart: always
    ports:
      - "8000:8000"
    networks:
      - cloud_network

networks:
  cloud_network:
    external: true
