version: '3'
services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - cloud

  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_volume:/var/lib/postgresql/data2
    restart: always
    ports:
      - "5433:5432"
    networks:
      - cloud

  cloud:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash run.sh
    container_name: cloud
    volumes:
      - .:/docker_django
    restart: always
    ports:
      - "8000:8000"
    environment:

      - POSTGRES_NAME2=postgres
      - POSTGRES_USER2=postgres
      - POSTGRES_PASSWORD2=postgres

      - POSTGRES_NAME1=postgres
      - POSTGRES_USER1=postgres
      - POSTGRES_PASSWORD1=postgres
    networks:
      - cloud
    depends_on:
      - postgres
      - postgresql

  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash run2.sh
    container_name: analysis
    volumes:
      - .:/docker_django
    restart: always
    ports:
      - "8001:8000"
    environment:

      - POSTGRES_NAME2=postgres
      - POSTGRES_USER2=postgres
      - POSTGRES_PASSWORD2=postgres

      - POSTGRES_NAME1=postgres
      - POSTGRES_USER1=postgres
      - POSTGRES_PASSWORD1=postgres
    networks:
      - cloud
    depends_on:
      - postgres
      - postgresql
      - cloud

volumes:
  postgres_volume:
  postgresql_volume:

networks:
  cloud: