# Generated by Django 3.2.9 on 2021-12-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.SmallIntegerField(default=0)),
                ('Name', models.CharField(max_length=200)),
                ('Platform', models.CharField(max_length=10)),
                ('Year', models.SmallIntegerField(default=0)),
                ('Genre', models.CharField(max_length=20)),
                ('Publisher', models.CharField(max_length=50)),
                ('NA_Sales', models.FloatField(default=0.0)),
                ('EU_Sales', models.FloatField(default=0.0)),
                ('JP_Sales', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('Other_Sales', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('Global_Sales', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
            ],
        ),
    ]
