# Generated by Django 3.2.9 on 2021-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Platform', models.CharField(max_length=10)),
                ('year', models.SmallIntegerField(default=0)),
                ('genre', models.CharField(max_length=20)),
                ('Publisher', models.CharField(max_length=20)),
                ('NA_Sales', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('EU_Sales', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('JP_Sales', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('Other_Sales', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('Global_Sales', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
            ],
        ),
    ]
